version: '3.2'

services:
  web:
    restart: always
    build: ./res
    container_name: lg
    expose:
      - "8000"
    ports:
            - "127.0.0.1:8000:8000"
    env_file: .env
    command: bash -c "rm -rd info.log ;python3 manage.py migrate ; python3 manage.py collectstatic --noinput ; gunicorn --bind 0.0.0.0:8000 ff.wsgi --log-file=- --error-logfile=- --access-logfile=- --log-level=debug --max-requests=500 --workers=3 --timeout=200"
    volumes:
            - ${PWD}/info.log:/app/info.log
            - ${PWD}/error.log:/app/error.log
            - ./res/:/app/

networks:
   default:
      external:
         name: lg-network

# volumes:
#         vl_name:
