# Generated by Django 3.2.9 on 2021-11-16 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNPRC', 'Unprocessed'), ('UNDPRC', 'UnderProcess'), ('PRC', 'Processed'), ('FLD', 'Failed'), ('CNL', 'Canceled')], default='UNPRC', max_length=10)),
                ('video_url', models.URLField(max_length=400, null=True, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Pointer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointer', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_url', models.URLField(default='', max_length=400)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.job')),
                ('pointer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.pointer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pointer',
            constraint=models.UniqueConstraint(fields=('job', 'pointer'), name='pointer-conflict'),
        ),
        migrations.AddConstraint(
            model_name='clip',
            constraint=models.UniqueConstraint(fields=('job', 'pointer'), name='clip-conflict'),
        ),
    ]
