# Generated by Django 3.2.9 on 2021-11-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('SCHED', 'Scheduled'), ('UNPRC', 'Unprocessed'), ('UNDPRC', 'UnderProcess'), ('PRC', 'Processed'), ('FLD', 'Failed'), ('CNL', 'Canceled')], default='SCHED', max_length=10),
        ),
    ]
