# Generated by Django 3.2.9 on 2021-12-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='failure_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
