# Generated by Django 3.2.9 on 2021-12-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20211201_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('UNPRC', 'Unprocessed'), ('SCHED', 'Scheduled'), ('UNDPRC', 'UnderProcess'), ('PRC', 'Processed'), ('FLD', 'Failed'), ('CNL', 'Canceled'), ('QUEUED', 'Queued')], default='UNPRC', max_length=10),
        ),
    ]
